GET http://localhost:5011/snippet

###

POST http://localhost:5011/snippet
Content-Type: application/json

{
      "id": 3,
      "language": "Python",
      "code": "class Circle:\n    def __init__(self, radius):\n        self.radius = radius\n\n    def area(self):\n        return 3.14 * self.radius ** 2"
}

###

DELETE http://localhost:5011/snippet/3
